services:
    mgilet.notification:
        class: Mgilet\NotificationBundle\Manager\NotificationManager
        arguments: ["@doctrine.orm.entity_manager", '@event_dispatcher', '@mgilet.notifiable_discovery', '%mgilet_notification.notification_class%']
        public: true

    mgilet.notifiable_discovery:
        class: Mgilet\NotificationBundle\NotifiableDiscovery
        arguments: [ '@doctrine.orm.entity_manager', '@annotation_reader']
        public: false

    mgilet.twig_extension:
            class: Mgilet\NotificationBundle\Twig\NotificationExtension
            arguments: ['@mgilet.notification', '@security.token_storage', '@twig', '@router']
            public: false
            tags:
                - { name: twig.extension }
